name: C/C++ CI

on:
  push:
    branches: [ "dungeon-master" ]
  pull_request:
    branches: [ "dungeon-master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: apt-get update
      run: sudo apt-get update
    - name: apt-get install
      run: sudo apt-get install -y emscripten imagemagick
    - name: make
      run: make
    - name: make test
      run: make test
